movie/task4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('task4_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

movie/task4_app/urls.py
from django.urls import path
from . import views
app_name = 'task4_app'
urlpatterns = [
    path('',views.index,name='index'),
    path('detail/<int:task4_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('edit/<int:id>/',views.edit,name='edit'),
    path('delete/<int:id>/',views.delete,name='delete'),
 ]

movie/task4_app/models.py
from django.db import models


# Create your models here.
class Task4(models.Model):
    name = models.CharField(max_length=255)
    desc = models.TextField()
    image = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie/task4_app/forms.py
from django import forms
from .models import Task4

class Task4_form(forms.ModelForm):
    class Meta:
        model = Task4
        fields = ['name','desc','image']

movie/task4_app/views.py
from django.shortcuts import render, redirect

import task4_app
from .forms import Task4_form
from .models import Task4


# Create your views here.
def index(request):
    task4 = Task4.objects.all()
    return render(request, 'index.html', {'task': task4})


def detail(request, task4_id):
    task4 = Task4.objects.get(id=task4_id)
    return render(request, 'detail.html', {'task4': task4})


def add(request):
   if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        image = request.FILES['image']
        task4 = Task4(name=name, desc=desc, image=image)
        task4.save()
        return redirect('/')
   return render(request, 'add.html',)


def edit(request, id):
    task4 = Task4.objects.get(id=id)
    form = Task4_form(request.POST or None, request.FILES,instance=task4)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'task4': task4,'form':form})


def delete(request,id):
    if request.method == 'POST':
        task4 = Task4.objects.get(id=id)
        task4.delete()
        return redirect('/')
    return render(request, 'delete.html')

movie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form  method="post" enctype="multipart/form-data" style="padding-left:10px"><br>
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br><br>
    <input type="text" name="desc" placeholder="Enter description"><br><br>
    <input type="file" name="image" ><br><br>
    <input type="submit" value="Add movie"  class="btn btn-dark">
</form>
{% endblock %}

movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">MOVIE TASK </a>
 <a href="{% url 'task4_app:add'%}" class="btn btn-light">Add Movies</a>

</nav>
{% block body %}

{% endblock %}

</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h3>Are u sure want to delete?</h3>
    <input type="submit" class="btn btn-primary" value="delete">
</form>
{% endblock %}

movie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container"><br>
    <div class="row">
        <div class="col-md-6">
            <img src="{{task4.image.url}}" height="400px" width="250px">
        </div>
        <div class="col-md-6">
            <h2>{{task4.name}}</h2><br>
            <h6>{{task4.desc}}</h6> <br>
            <a href="{% url 'task4_app:edit' task4.id %}" class="btn btn-dark">Update</a>
            <a href="{% url 'task4_app:delete' task4.id %}" class="btn btn-danger">Delete</a>

        </div>
    </div>
</div>
{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
 {% csrf_token %}
 {{form.as_p}}
    <input type="submit" value="edit" class ="btn btn-secondary">



</form>
 {% endblock %}

movie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
   <div class="row">

 {% for i in task %}
    <div class="col-md-4">
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="{{i.image.url}}" height="200px" width="200px" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">{{i.name}}</h5>
        <p class="card-text">{{i.desc}}</p>
        <a href="{% url 'task4_app:detail' i.id  %}"  class="btn btn-primary">Get Details</a>
      </div>
    </div><br>
    </div>
 {% endfor %}

    </div>
</div>
{% endblock %}

<!--{% for i in task %}-->
<!--  {{i.name}}<br>-->
<!-- {{i.desc}}<br>-->
<!-- <img src = "{{i.image.url}}" height="100px" width="100px" >-->
<!--{% endfor %}-->